/*
 * This file is generated by jOOQ.
 */
package my.groupId.jooq;


import my.groupId.jooq.tables.Book;
import my.groupId.jooq.tables.FlywaySchemaHistory;
import my.groupId.jooq.tables.Rent;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in library.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index BOOK_AUTHORID = Internal.createIndex(DSL.name("authorId"), Book.BOOK, new OrderField[] { Book.BOOK.AUTHORID }, false);
    public static final Index RENT_BOOKID = Internal.createIndex(DSL.name("bookId"), Rent.RENT, new OrderField[] { Rent.RENT.BOOKID }, false);
    public static final Index BOOK_CATEGORYID = Internal.createIndex(DSL.name("categoryId"), Book.BOOK, new OrderField[] { Book.BOOK.CATEGORYID }, false);
    public static final Index FLYWAY_SCHEMA_HISTORY_FLYWAY_SCHEMA_HISTORY_S_IDX = Internal.createIndex(DSL.name("flyway_schema_history_s_idx"), FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, new OrderField[] { FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.SUCCESS }, false);
    public static final Index BOOK_PUBLISHERID = Internal.createIndex(DSL.name("publisherId"), Book.BOOK, new OrderField[] { Book.BOOK.PUBLISHERID }, false);
    public static final Index RENT_USERID = Internal.createIndex(DSL.name("userId"), Rent.RENT, new OrderField[] { Rent.RENT.USERID }, false);
}
