/*
 * This file is generated by jOOQ.
 */
package my.groupId.jooq;


import my.groupId.jooq.tables.Admin;
import my.groupId.jooq.tables.Author;
import my.groupId.jooq.tables.Book;
import my.groupId.jooq.tables.Category;
import my.groupId.jooq.tables.FlywaySchemaHistory;
import my.groupId.jooq.tables.Publisher;
import my.groupId.jooq.tables.Rent;
import my.groupId.jooq.tables.Setting;
import my.groupId.jooq.tables.Users;


/**
 * Convenience access to all tables in library.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>library.admin</code>.
     */
    public static final Admin ADMIN = Admin.ADMIN;

    /**
     * The table <code>library.author</code>.
     */
    public static final Author AUTHOR = Author.AUTHOR;

    /**
     * The table <code>library.book</code>.
     */
    public static final Book BOOK = Book.BOOK;

    /**
     * The table <code>library.category</code>.
     */
    public static final Category CATEGORY = Category.CATEGORY;

    /**
     * The table <code>library.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>library.publisher</code>.
     */
    public static final Publisher PUBLISHER = Publisher.PUBLISHER;

    /**
     * The table <code>library.rent</code>.
     */
    public static final Rent RENT = Rent.RENT;

    /**
     * The table <code>library.setting</code>.
     */
    public static final Setting SETTING = Setting.SETTING;

    /**
     * The table <code>library.users</code>.
     */
    public static final Users USERS = Users.USERS;
}
