/*
 * This file is generated by jOOQ.
 */
package my.groupId.jooq.tables.records;


import java.time.LocalDateTime;

import my.groupId.jooq.tables.Admin;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AdminRecord extends UpdatableRecordImpl<AdminRecord> implements Record7<Long, String, String, LocalDateTime, LocalDateTime, Long, Long> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>library.admin.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>library.admin.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>library.admin.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>library.admin.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>library.admin.password</code>.
     */
    public void setPassword(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>library.admin.password</code>.
     */
    public String getPassword() {
        return (String) get(2);
    }

    /**
     * Setter for <code>library.admin.createdAt</code>.
     */
    public void setCreatedat(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>library.admin.createdAt</code>.
     */
    public LocalDateTime getCreatedat() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>library.admin.updatedAt</code>.
     */
    public void setUpdatedat(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>library.admin.updatedAt</code>.
     */
    public LocalDateTime getUpdatedat() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>library.admin.createdBy</code>.
     */
    public void setCreatedby(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>library.admin.createdBy</code>.
     */
    public Long getCreatedby() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>library.admin.updatedBy</code>.
     */
    public void setUpdatedby(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>library.admin.updatedBy</code>.
     */
    public Long getUpdatedby() {
        return (Long) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<Long, String, String, LocalDateTime, LocalDateTime, Long, Long> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<Long, String, String, LocalDateTime, LocalDateTime, Long, Long> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Admin.ADMIN.ID;
    }

    @Override
    public Field<String> field2() {
        return Admin.ADMIN.NAME;
    }

    @Override
    public Field<String> field3() {
        return Admin.ADMIN.PASSWORD;
    }

    @Override
    public Field<LocalDateTime> field4() {
        return Admin.ADMIN.CREATEDAT;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return Admin.ADMIN.UPDATEDAT;
    }

    @Override
    public Field<Long> field6() {
        return Admin.ADMIN.CREATEDBY;
    }

    @Override
    public Field<Long> field7() {
        return Admin.ADMIN.UPDATEDBY;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getPassword();
    }

    @Override
    public LocalDateTime component4() {
        return getCreatedat();
    }

    @Override
    public LocalDateTime component5() {
        return getUpdatedat();
    }

    @Override
    public Long component6() {
        return getCreatedby();
    }

    @Override
    public Long component7() {
        return getUpdatedby();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getPassword();
    }

    @Override
    public LocalDateTime value4() {
        return getCreatedat();
    }

    @Override
    public LocalDateTime value5() {
        return getUpdatedat();
    }

    @Override
    public Long value6() {
        return getCreatedby();
    }

    @Override
    public Long value7() {
        return getUpdatedby();
    }

    @Override
    public AdminRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public AdminRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public AdminRecord value3(String value) {
        setPassword(value);
        return this;
    }

    @Override
    public AdminRecord value4(LocalDateTime value) {
        setCreatedat(value);
        return this;
    }

    @Override
    public AdminRecord value5(LocalDateTime value) {
        setUpdatedat(value);
        return this;
    }

    @Override
    public AdminRecord value6(Long value) {
        setCreatedby(value);
        return this;
    }

    @Override
    public AdminRecord value7(Long value) {
        setUpdatedby(value);
        return this;
    }

    @Override
    public AdminRecord values(Long value1, String value2, String value3, LocalDateTime value4, LocalDateTime value5, Long value6, Long value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AdminRecord
     */
    public AdminRecord() {
        super(Admin.ADMIN);
    }

    /**
     * Create a detached, initialised AdminRecord
     */
    public AdminRecord(Long id, String name, String password, LocalDateTime createdat, LocalDateTime updatedat, Long createdby, Long updatedby) {
        super(Admin.ADMIN);

        setId(id);
        setName(name);
        setPassword(password);
        setCreatedat(createdat);
        setUpdatedat(updatedat);
        setCreatedby(createdby);
        setUpdatedby(updatedby);
    }
}
