/*
 * This file is generated by jOOQ.
 */
package my.groupId.jooq.tables.records;


import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;

import my.groupId.jooq.tables.Rent;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RentRecord extends UpdatableRecordImpl<RentRecord> implements Record10<Long, Long, Long, LocalDate, LocalDate, LocalDateTime, LocalDateTime, Long, Long, BigDecimal> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>library.rent.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>library.rent.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>library.rent.bookId</code>.
     */
    public void setBookid(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>library.rent.bookId</code>.
     */
    public Long getBookid() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>library.rent.userId</code>.
     */
    public void setUserid(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>library.rent.userId</code>.
     */
    public Long getUserid() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>library.rent.startDate</code>.
     */
    public void setStartdate(LocalDate value) {
        set(3, value);
    }

    /**
     * Getter for <code>library.rent.startDate</code>.
     */
    public LocalDate getStartdate() {
        return (LocalDate) get(3);
    }

    /**
     * Setter for <code>library.rent.endDate</code>.
     */
    public void setEnddate(LocalDate value) {
        set(4, value);
    }

    /**
     * Getter for <code>library.rent.endDate</code>.
     */
    public LocalDate getEnddate() {
        return (LocalDate) get(4);
    }

    /**
     * Setter for <code>library.rent.createdAt</code>.
     */
    public void setCreatedat(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>library.rent.createdAt</code>.
     */
    public LocalDateTime getCreatedat() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>library.rent.updatedAt</code>.
     */
    public void setUpdatedat(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>library.rent.updatedAt</code>.
     */
    public LocalDateTime getUpdatedat() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>library.rent.createdBy</code>.
     */
    public void setCreatedby(Long value) {
        set(7, value);
    }

    /**
     * Getter for <code>library.rent.createdBy</code>.
     */
    public Long getCreatedby() {
        return (Long) get(7);
    }

    /**
     * Setter for <code>library.rent.updatedBy</code>.
     */
    public void setUpdatedby(Long value) {
        set(8, value);
    }

    /**
     * Getter for <code>library.rent.updatedBy</code>.
     */
    public Long getUpdatedby() {
        return (Long) get(8);
    }

    /**
     * Setter for <code>library.rent.fines</code>.
     */
    public void setFines(BigDecimal value) {
        set(9, value);
    }

    /**
     * Getter for <code>library.rent.fines</code>.
     */
    public BigDecimal getFines() {
        return (BigDecimal) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row10<Long, Long, Long, LocalDate, LocalDate, LocalDateTime, LocalDateTime, Long, Long, BigDecimal> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    @Override
    public Row10<Long, Long, Long, LocalDate, LocalDate, LocalDateTime, LocalDateTime, Long, Long, BigDecimal> valuesRow() {
        return (Row10) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Rent.RENT.ID;
    }

    @Override
    public Field<Long> field2() {
        return Rent.RENT.BOOKID;
    }

    @Override
    public Field<Long> field3() {
        return Rent.RENT.USERID;
    }

    @Override
    public Field<LocalDate> field4() {
        return Rent.RENT.STARTDATE;
    }

    @Override
    public Field<LocalDate> field5() {
        return Rent.RENT.ENDDATE;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return Rent.RENT.CREATEDAT;
    }

    @Override
    public Field<LocalDateTime> field7() {
        return Rent.RENT.UPDATEDAT;
    }

    @Override
    public Field<Long> field8() {
        return Rent.RENT.CREATEDBY;
    }

    @Override
    public Field<Long> field9() {
        return Rent.RENT.UPDATEDBY;
    }

    @Override
    public Field<BigDecimal> field10() {
        return Rent.RENT.FINES;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getBookid();
    }

    @Override
    public Long component3() {
        return getUserid();
    }

    @Override
    public LocalDate component4() {
        return getStartdate();
    }

    @Override
    public LocalDate component5() {
        return getEnddate();
    }

    @Override
    public LocalDateTime component6() {
        return getCreatedat();
    }

    @Override
    public LocalDateTime component7() {
        return getUpdatedat();
    }

    @Override
    public Long component8() {
        return getCreatedby();
    }

    @Override
    public Long component9() {
        return getUpdatedby();
    }

    @Override
    public BigDecimal component10() {
        return getFines();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getBookid();
    }

    @Override
    public Long value3() {
        return getUserid();
    }

    @Override
    public LocalDate value4() {
        return getStartdate();
    }

    @Override
    public LocalDate value5() {
        return getEnddate();
    }

    @Override
    public LocalDateTime value6() {
        return getCreatedat();
    }

    @Override
    public LocalDateTime value7() {
        return getUpdatedat();
    }

    @Override
    public Long value8() {
        return getCreatedby();
    }

    @Override
    public Long value9() {
        return getUpdatedby();
    }

    @Override
    public BigDecimal value10() {
        return getFines();
    }

    @Override
    public RentRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public RentRecord value2(Long value) {
        setBookid(value);
        return this;
    }

    @Override
    public RentRecord value3(Long value) {
        setUserid(value);
        return this;
    }

    @Override
    public RentRecord value4(LocalDate value) {
        setStartdate(value);
        return this;
    }

    @Override
    public RentRecord value5(LocalDate value) {
        setEnddate(value);
        return this;
    }

    @Override
    public RentRecord value6(LocalDateTime value) {
        setCreatedat(value);
        return this;
    }

    @Override
    public RentRecord value7(LocalDateTime value) {
        setUpdatedat(value);
        return this;
    }

    @Override
    public RentRecord value8(Long value) {
        setCreatedby(value);
        return this;
    }

    @Override
    public RentRecord value9(Long value) {
        setUpdatedby(value);
        return this;
    }

    @Override
    public RentRecord value10(BigDecimal value) {
        setFines(value);
        return this;
    }

    @Override
    public RentRecord values(Long value1, Long value2, Long value3, LocalDate value4, LocalDate value5, LocalDateTime value6, LocalDateTime value7, Long value8, Long value9, BigDecimal value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RentRecord
     */
    public RentRecord() {
        super(Rent.RENT);
    }

    /**
     * Create a detached, initialised RentRecord
     */
    public RentRecord(Long id, Long bookid, Long userid, LocalDate startdate, LocalDate enddate, LocalDateTime createdat, LocalDateTime updatedat, Long createdby, Long updatedby, BigDecimal fines) {
        super(Rent.RENT);

        setId(id);
        setBookid(bookid);
        setUserid(userid);
        setStartdate(startdate);
        setEnddate(enddate);
        setCreatedat(createdat);
        setUpdatedat(updatedat);
        setCreatedby(createdby);
        setUpdatedby(updatedby);
        setFines(fines);
    }
}
