/*
 * This file is generated by jOOQ.
 */
package my.groupId.jooq.tables;


import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import my.groupId.jooq.Keys;
import my.groupId.jooq.Library;
import my.groupId.jooq.tables.records.SettingRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row9;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Setting extends TableImpl<SettingRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>library.setting</code>
     */
    public static final Setting SETTING = new Setting();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SettingRecord> getRecordType() {
        return SettingRecord.class;
    }

    /**
     * The column <code>library.setting.id</code>.
     */
    public final TableField<SettingRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>library.setting.userIssuedLimit</code>.
     */
    public final TableField<SettingRecord, Integer> USERISSUEDLIMIT = createField(DSL.name("userIssuedLimit"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>library.setting.bookReturnDay</code>.
     */
    public final TableField<SettingRecord, Integer> BOOKRETURNDAY = createField(DSL.name("bookReturnDay"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>library.setting.currency</code>.
     */
    public final TableField<SettingRecord, String> CURRENCY = createField(DSL.name("currency"), SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>library.setting.oneDayFee</code>.
     */
    public final TableField<SettingRecord, BigDecimal> ONEDAYFEE = createField(DSL.name("oneDayFee"), SQLDataType.DECIMAL(4, 2), this, "");

    /**
     * The column <code>library.setting.createdAt</code>.
     */
    public final TableField<SettingRecord, LocalDateTime> CREATEDAT = createField(DSL.name("createdAt"), SQLDataType.LOCALDATETIME(0), this, "");

    /**
     * The column <code>library.setting.updatedAt</code>.
     */
    public final TableField<SettingRecord, LocalDateTime> UPDATEDAT = createField(DSL.name("updatedAt"), SQLDataType.LOCALDATETIME(0), this, "");

    /**
     * The column <code>library.setting.createdBy</code>.
     */
    public final TableField<SettingRecord, Long> CREATEDBY = createField(DSL.name("createdBy"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>library.setting.updatedBy</code>.
     */
    public final TableField<SettingRecord, Long> UPDATEDBY = createField(DSL.name("updatedBy"), SQLDataType.BIGINT, this, "");

    private Setting(Name alias, Table<SettingRecord> aliased) {
        this(alias, aliased, null);
    }

    private Setting(Name alias, Table<SettingRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>library.setting</code> table reference
     */
    public Setting(String alias) {
        this(DSL.name(alias), SETTING);
    }

    /**
     * Create an aliased <code>library.setting</code> table reference
     */
    public Setting(Name alias) {
        this(alias, SETTING);
    }

    /**
     * Create a <code>library.setting</code> table reference
     */
    public Setting() {
        this(DSL.name("setting"), null);
    }

    public <O extends Record> Setting(Table<O> child, ForeignKey<O, SettingRecord> key) {
        super(child, key, SETTING);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Library.LIBRARY;
    }

    @Override
    public Identity<SettingRecord, Long> getIdentity() {
        return (Identity<SettingRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<SettingRecord> getPrimaryKey() {
        return Keys.KEY_SETTING_PRIMARY;
    }

    @Override
    public List<UniqueKey<SettingRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_SETTING_ID);
    }

    @Override
    public Setting as(String alias) {
        return new Setting(DSL.name(alias), this);
    }

    @Override
    public Setting as(Name alias) {
        return new Setting(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Setting rename(String name) {
        return new Setting(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Setting rename(Name name) {
        return new Setting(name, null);
    }

    // -------------------------------------------------------------------------
    // Row9 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row9<Long, Integer, Integer, String, BigDecimal, LocalDateTime, LocalDateTime, Long, Long> fieldsRow() {
        return (Row9) super.fieldsRow();
    }
}
